server:
  port: 9090
spring:
  application:
    name: api-gateway
    zipkin:
      base-url: http://www.lyy.com:9411
      sender:
        type: web
      enabled: true
    sleuth:
      sampler:
        probability: 1

zuul:
  routes:
    product:
      path: /product/**
      serviceId: product
      sensitiveHeaders:
  strip-prefix: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000


logging:
  level:
    org.springframework.cloud.openfeign: debug
