spring:
  application:
    name: order
  zipkin:
    base-url: http://www.lyy.com:9411
    sender:
      type: web
    enabled: true
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
server:
  port: 8081


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      circuitBreaker:
        requestVolumeThreshold: 20
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50
      metrics:
        rollingStats:
          timeInMilliseconds: 10000


logging:
  level:
    org.springframework.cloud.openfeign: debug
    
management:
  endpoints:
    web:
      exposure:
        include: "*"


env: 2
