
spring:
  application:
    name: product
  zipkin:
    base-url: http://www.lyy.com:9411
    sender:
      type: web
    enabled: true
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    virtual-host: /
    ###开启消息确认机制 confirms
    publisher-confirms: true
    publisher-returns: true


server:
  port: 8085

logging:
  level:
    org.springframework.cloud.openfeign: debug
