
spring:
  application:
    name: product
    zipkin:
      base-url: http://www.lyy.com:9411
      sender:
        type: web
      enabled: true
    sleuth:
      sampler:
        probability: 1


server:
  port: 8080

logging:
  level:
    org.springframework.cloud.openfeign: debug
